export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "@/styles/globals.css";
import QueryProvider from "@/components/shared/QueryProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
